[General]

[Rule]
FINAL,DIRECT

[Header Rewrite]
http-response ^https?:\/\/(?:[^\/]+\.)?island\.is(?:[:\/?#]|$) header-replace-regex 060107 060107 060106
http-response ^https?:\/\/(?:[^\/]+\.)?island\.is(?:[:\/?#]|$) header-replace 060107 060106

[Body Rewrite]
http-response ^https?:\/\/(?:[^\/]+\.)?island\.is(?:[:\/?#]|$) 060107 060106

[MITM]
h2 = true
hostname = *.island.is, island.is
