[General]

[Rule]
FINAL,DIRECT

[Header Rewrite]
http-response ^https?:\/\/(?:[^\/]+\.)?(?:island\.is|landsbankinn\.is|arionbanki\.is)(?:[:\/?#]|$) header-replace 210507 210506

[Body Rewrite]
http-response ^https?:\/\/(?:[^\/]+\.)?(?:island\.is|landsbankinn\.is|arionbanki\.is)(?:[:\/?#]|$) 210507 210506

[MITM]
skip-server-cert-verify = true
h2 = true
hostname = island.is, *.island.is, landsbankinn.is, *.landsbankinn.is, arionbanki.is, *.arionbanki.is
